config/routes.rb
MentorhipLite::Application.routes.draw do
 
  devise_for :users
  
  resources :users
  get 'users/:id' => 'users#show'

  #get "users/:id"

  resources :courses 

  root to: "courses#index"

  match '/s' => 's#index', :via => [:get], :as => '/s/'


  get 'courses/search' => 'courses#search', :as => :courses_search

 #get '/courses/:course_type', to: 'courses#search'

 

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/course.rb
class Course < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :name, :course_type, :description, :photo1, :state, :photo1_file_name

  mount_uploader :photo1, Photo1Uploader



#has_attached_file :photo1, :styles => { :medium => "300x300>", :thumb => "100x100>" }#, :default_url => "/images/course/.png"


def self.search(search)
	if search
		find(:all, :conditions => ['course_type LIKE ?', "%#{search}%"], :order =>'created_at DESC')
	else
		find(:all)
	end
end



def to_param
    "#{id}-#{name}"
  end

end

app/models/course_time.rb
class CourseTime < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 has_attached_file :profile_pic, :styles => { :medium => "250x250>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  
 has_many :courses

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception




end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

#before_filter :authenticate_user, :except => [:show, :index]

before_action :set_course, only: [:show, :edit, :update, :destroy]


#before_filter :authenticate_user!

def index
  #@search = Course.search(params[:q])
  #@courses = @search.result
  @courses = Course.all(:order => "created_at DESC")
  @courses = Course.search(params[:search]) 
  @courses = Course.order('created_at DESC').page params[:page]
  

  #respond_to do |format|
        #format.html
        #format.json {render json: @courses}
        #format.xml {render xml: @courses}
  #end
end

def new
  @course = Course.new
end


def create
  @course = Course.new(course_params)
  respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created }

        format.json { render action: 'show', status: :created, location: @recipe }
      else
         format.html { render action: 'new' }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end



  #render text: params[:course].inspect
  #@course = Course.new(params[:id])

end

def show
    @course = Course.find(params[:id])
    respond_to do |format|
      format.html
      format.json {render json: @course}
    end
end


def edit
 if current_user != @course.user
    
  else
    redirect_to root_path, notice: "You are not authorized to edit this course."
  end
  end


def update
 respond_to do |format|
   if @course.update(course_params) 
     format.html{redirect_to @course, notice: 'Course successfully updated.'}
     format.json{head :no_content}
   else
     format.html{render action: 'edit'}
     format.json {render json: @course.errors, status: :unprocessable_entity }
   end
 end
end

def destroy
@course.destroy
  respond_to do |format|
    format.html { redirect_to courses_url }
    format.json { head :no_content }
  end
 end


def search
  @courses = Course.search(params[:search]) 

  respond_to do |format|
      format.html
      format.json {render json: @course}
    end
end




 private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :course_type, :price, :address1, :address2, :city, :state, :zipcode, :photo1, :photo2, :photo3, :min_age, :max_age, :min_class_size, :max_class_size, :required_gear, :required_gear_desc, :cancellation, :photo1_cache, :remove_photo1)
    end

end

app/controllers/s_controller.rb
class SController < ApplicationController

def index


@courses = Course.search(params[:search])
#@courses = @search.result

end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
@users = User.all(:order => "created_at DESC")
end


def show  
@user = User.find(params[:id])
end
	


end

app/helpers/application_helper.rb
module ApplicationHelper

include CoursesHelper

end

app/helpers/courses_helper.rb
module CoursesHelper

def us_states
  [
    ['AK', 'AK'],
    ['AL', 'AL'],
    ['AR', 'AR'],
    ['AZ', 'AZ'],
    ['CA', 'CA'],
    ['CO', 'CO'],
    ['CT', 'CT'],
    ['DC', 'DC'],
    ['DE', 'DE'],
    ['FL', 'FL'],
    ['GA', 'GA'],
    ['HI', 'HI'],
    ['IA', 'IA'],
    ['ID', 'ID'],
    ['IL', 'IL'],
    ['IN', 'IN'],
    ['KS', 'KS'],
    ['KY', 'KY'],
    ['LA', 'LA'],
    ['MA', 'MA'],
    ['MD', 'MD'],
    ['ME', 'ME'],
    ['MI', 'MI'],
    ['MN', 'MN'],
    ['MO', 'MO'],
    ['MS', 'MS'],
    ['MT', 'MT'],
    ['NC', 'NC'],
    ['ND', 'ND'],
    ['NE', 'NE'],
    ['NH', 'NH'],
    ['NJ', 'NJ'],
    ['NM', 'NM'],
    ['NV', 'NV'],
    ['NY', 'NY'],
    ['OH', 'OH'],
    ['OK', 'OK'],
    ['OR', 'OR'],
    ['PA', 'PA'],
    ['RI', 'RI'],
    ['SC', 'SC'],
    ['SD', 'SD'],
    ['TN', 'TN'],
    ['TX', 'TX'],
    ['UT', 'UT'],
    ['VA', 'VA'],
    ['VT', 'VT'],
    ['WA', 'WA'],
    ['WI', 'WI'],
    ['WV', 'WV'],
    ['WY', 'WY']
  ]
end



end

app/helpers/s_helper.rb
module SHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<div id="course">
<h1>Add a Course</h1>
<%= form_for @course, :html => {:multipart => true } do |f| %>

  <div class="field_ken">
    <%= f.label :name %><br>
    <%= f.text_field :name, :size => 45 %>
  </div>
  <div class="field">
    <%= f.label :course_type, "Course Type" %><br>
    <%= f.text_field :course_type %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <div><%= f.text_area :description, :cols => "50", :rows => "6" %></div>
  </div>

  <div class="field">
    <%= f.label :price %><br>
    <div><%= f.number_field :price %></div>
  </div>


    <div class="field">
    <%= f.label :address1 %><br>
    <div><%= f.text_field :address1 %></div>
  </div>

    <div class="field">
    <%= f.label :address2 %><br>
    <div><%= f.text_field :address2 %></div>
  </div>

    <div class="field">
    <%= f.label :city %><br>
    <div><%= f.text_field :city %></div>
  </div>

    <div class="field">
    <%= f.label :state %><br>
    <div><%= f.select :state, options_for_select(us_states) %></div>
  </div>

    <div class="field">
    <%= f.label :zipcode %><br>
    <div><%= f.number_field :zipcode, :min =>'00000', :max =>'99999'%></div>
  </div>

   <div class="field">
    <%= f.label :photo1 %><br>
    <div><%=f.file_field :photo1 %></div>
  </div>

  <div class="field">
    <%= f.label :photo2 %><br>
    <div><%= f.text_field :photo2 %></div>
  </div>

  <div class="field">
    <%= f.label :photo3 %><br>
    <div><%= f.text_field :photo3 %></div>
  </div>

  <div class="field">
    <%= f.label "Minimum Age" %><br>
    <div><%= f.number_field :min_age %></div>
  </div>

  <div class="field">
    <%= f.label "Maximum Age" %><br>
    <div><%= f.number_field :max_age %></div>
  </div>

  <div class="field">
    <%= f.label :min_class_size %><br>
    <div><%= f.number_field :min_class_size %></div>
  </div>

  <div class="field">
    <%= f.label :max_class_size %><br>
    <div><%= f.number_field :max_class_size %></div>
  </div>

  <div class="field" id="required_gear">
    <%= f.label :required_gear %><br>
    <div><%= f.check_box :required_gear %></div>
  </div>

  <div class="required_gear_desc">
    <%= f.label :required_gear_desc %><br>
    <div><%= f.text_area :required_gear_desc %></div>
  </div>

  <div class="field">
    <%= f.label :cancellation %><br>
    <div><%= f.text_area :cancellation %></div>
  </div>




 <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

</div>

app/views/courses/courses.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MentorhipLite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
</header>
<div class="container_front">

<%= yield %>
</div><!-- end container -->


<footer>
</footer>
</body>

app/views/courses/courses_home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MentorhipLite</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
</header>

<footer>
</footer>
</body>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<div class="container_front">

<div id="front_search_wrapper">

<div id="front_search">
<%#=search_form_for @search do |f| %>


<div class="field" id="front_search">
    <%#= f.label :name_cont %>
    <%#= f.text_field :name_cont %>
  </div>

<div class="field" id="front_search">
    <%#= f.label :name_cont %><br>
    <%#= f.text_field :name_cont %>
  </div>

 <div class="actions" id="front_search">
    <%#= f.submit "Search" %>
</div>

<%# end %>

</div><!-- end front_search -->
</div><!-- end front_search_container -->



<%# for course in @courses %>
    <h1><%#=link_to course.name, course %></h1>
    <%#=course.course_type %>

<%# end %>

<div class="courses_feed">

  <div id="courses_feed_single">
    <% @courses.each do |course| %>
    <div id="col_left">
    <%= image_tag course.photo1_url %>
    </div><!-- end col_left -->

    <div id="col_right">
    <h1><%=link_to course.name, course %></h1>
    <%=course.course_type %>
    <%=course.price %>
    
    <%=truncate(course.description)%>
    <%=course.city %>
    </div><!-- end col_right -->


  <div><!-- end courses_feed_single -->
  <div id="clear"></div>
  
  <% end %>

</div><!-- end courses_feed -->

</div><!-- end container_front -->


<%= paginate @courses %>

app/views/courses/new.html.erb
<%= render 'form' %>


<%= link_to 'Back', courses_path %>

app/views/courses/search.html.erb
<%-@courses.each do |course| %>
 
<div class="courses_feed">

  <div id="courses_feed_single">
    <% @courses.each do |course| %>
    <div id="col_left">
    test
    </div><!-- end col_left -->

    <div id="col_right">
    <h1><%=link_to course.name, course %></h1>
    <%=course.course_type %>
    <%=course.price %>
    <%=truncate(course.description)%>
    <%=course.city %>
    </div><!-- end col_right -->


  <div><!-- end courses_feed_single -->
  <div id="clear"></div>
  
  <% end %>

</div><!-- end courses_feed -->

app/views/courses/show.html.erb
<div id="course">

<div style="border:1px solid #000;padding:15px;">

<%= @course.photo1_file_name %>

<h1><%=@course.name%></h1></br>
<p id="notice"><%= notice %></p>

<p>
  <div style="display:inline;"><strong>Name:</strong>
  <h1><%= @course.name %></h1> </div>
</p>

<p>
  <strong>Type:</strong>
  <%= @course.course_type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @course.price %>
</p>

<p>
  <strong>Address 1:</strong>
  <%= @course.address1 %>
</p>

<p>
  <strong>Address 2:</strong>
  <%= @course.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @course.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @course.state %>
</p>

<p>
  <strong>Photo 1:</strong>
  <%= image_tag @course.photo1_url %>
</p>

<p>
  <strong>Photo 2:</strong>
  <%= @course.photo2 %>
</p>

<p>
  <strong>Photo 3:</strong>
  <%= @course.photo3 %>
</p>

<p>
  <strong>Minimum Age:</strong>
  <%= @course.min_age %>
</p>

<p>
  <strong>Maximum Age:</strong>
  <%= @course.max_age %>
</p>

<p>
  <strong>Minimum Class Size:</strong>
  <%= @course.min_class_size %>
</p>


<p>
  <strong>Maximum Class Size:</strong>
  <%= @course.max_class_size %>
</p>

<p>
  <strong>Required Gear:</strong>
  <%= @course.required_gear %>
</p>

<p>
  <strong>Required Gear:</strong>
  <%= @course.required_gear_desc %>
</p>

<p>
  <strong>Cancellation Policy:</strong>
  <%= @course.cancellation %>
</p>

<% if user_signed_in? %>
<%= link_to 'Edit', edit_course_path %>
<%= link_to 'Destroy', @course, :confirm => 'Are you sure?', :method => :destroy %>

<% end %>

</div><!-- end -->

</div><!-- end course -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MentorhipLite</title>
  <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>


</head>
<body>
<header>
<div id="header_container">

<div id="header_left">

<div id="logo">
<%= link_to image_tag('Mentorhip_logo.png').html_safe, root_url %>

</div>




<div id="top_search">
<%= form_tag s_path, :method => 'get' do %>
<form>
<div class="field" id="top_search_input">
      <%= text_field_tag :search, params[:search] %>
  </div>

 <div class="actions" id="top_search_input">
    <%= submit_tag "Search", :name => nil %>
</div>
</form>

<% end %>


</div><!-- end top_search -->
</div><!-- end header_left -->


<div id="header_right">
<nav>
	<div class="menu">
			<ul>
		

				<% if user_signed_in? %>
  				<li class="dropdown">
            	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
              	My Account<b class="caret"></b></a>
            	<ul class="dropdown-menu">
            	<li><%= link_to('Dashboard', edit_user_registration_path) %></li>
              	<li><a href="#">Action</a></li>
              	<li><a href="#">Another action</a></li>
              	<li><a href="#">Something else here</a></li>
              	<li class="divider"></li>
              	<li><a href="#">Separated link</a></li>
            	</ul>
          		</li>
 

				<% else %>
  				<li><%= link_to('Sign-Up', new_user_registration_path)  %></li>
				<% end %>

				<% if user_signed_in? %>
  				<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
				<% else %>
  				<li><%= link_to('Login', new_user_session_path)  %></li>
				<% end %>
				<li><%= button_to "Add a Course", new_course_path, :class => "button", :method => :get  %></li>
				
			</ul>
		</div>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</nav>
</div><!-- end header_right -->
</div><!-- end header_container -->


</header>

<div id="container">
<%= yield %>
</div><!-- end container -->

<footer>
</footer>

</body>

app/views/s/index.html.erb
<h1>testing</h1>

<div id ="wrapper">

Hello World!

<div class="courses_feed">

  <div id="courses_feed_single">
    <% @courses.each do |course| %>
    <div id="col_left">
    <%= image_tag course.photo1_url %>
    </div><!-- end col_left -->

    <div id="col_right">
    <h1><%=link_to course.name, course %></h1>
    <%=course.course_type %>
    <%=course.price %>
    
    <%=truncate(course.description)%>
    <%=course.city %>
    </div><!-- end col_right -->


  <div><!-- end courses_feed_single -->
  <div id="clear"></div>
  
  <% end %>




</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <div id="col_left">
    <%=user.profile_pic %>
    test
    </div><!-- end col_left -->

    <div id="col_right">
    <h1><%=user.firstname %></h1>
    <%#=course.course_type %>
    <%#=course.price %>
    <%#=truncate(course.description)%>
    <%#=course.city %>
    </div><!-- end col_right -->


  <div><!-- end courses_feed_single -->
  <div id="clear"></div>
  
  <% end %>

app/views/users/new.html.erb
<%#= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
  <%#= form.file_field :profile_pic %>
<%# end %>

<h1>Hello World</h1>